### ISSUE TITLE
TODO: 5.15 Disable Fast User Switching

### ISSUE THREAD

**Issue by krispayne** [krispayne/CIS-Settings#26]
test new code

**Comment by tonytranupc** [comment]
If you are using Windows 10, here is [how to disable Fast User Switching feature in Windows 10](https://usefulpcguide.com/18658/how-to-disable-fast-user-switching-windows-10/). Check it out! It's very easy and quick by using Local Group Policy Editor or Registry Editor. Both are working the same to disable this function in Windows 10.
